# coding: utf-8

"""
    PowerManifest Affirmations API

    API for managing personalized affirmations in the PowerManifest life coaching app

    The version of the OpenAPI document: 1.0.0
    Contact: api@powermanifest.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AffirmationCategory(str, Enum):
    """
    AffirmationCategory
    """

    """
    allowed enum values
    """
    FINANCIAL_FREEDOM = 'financial_freedom'
    LOVE_RELATIONSHIPS = 'love_relationships'
    HEALTH_ENERGY = 'health_energy'
    CAREER_SUCCESS = 'career_success'
    CONFIDENCE_GROWTH = 'confidence_growth'
    INNER_PEACE_SPIRITUAL = 'inner_peace_spiritual'
    FAMILY_PARENTING = 'family_parenting'
    CUSTOM = 'custom'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AffirmationCategory from a JSON string"""
        return cls(json.loads(json_str))


