# coding: utf-8

"""
    PowerManifest Affirmations API

    API for managing personalized affirmations in the PowerManifest life coaching app

    The version of the OpenAPI document: 1.0.0
    Contact: api@powermanifest.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from models.affirmation.schedule_config_time_slots_inner import ScheduleConfigTimeSlotsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ScheduleConfig(BaseModel):
    """
    ScheduleConfig
    """ # noqa: E501
    enabled: StrictBool = Field(description="Whether scheduling is active")
    time_slots: Optional[List[ScheduleConfigTimeSlotsInner]] = Field(default=None, description="Specific times to send notifications")
    frequency: Optional[StrictStr] = 'daily'
    notification_type: Optional[StrictStr] = 'push_notification'
    __properties: ClassVar[List[str]] = ["enabled", "time_slots", "frequency", "notification_type"]

    @field_validator('frequency')
    def frequency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('daily', 'weekly', 'custom',):
            raise ValueError("must be one of enum values ('daily', 'weekly', 'custom')")
        return value

    @field_validator('notification_type')
    def notification_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('push_notification', 'email', 'both',):
            raise ValueError("must be one of enum values ('push_notification', 'email', 'both')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScheduleConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in time_slots (list)
        _items = []
        if self.time_slots:
            for _item in self.time_slots:
                if _item:
                    _items.append(_item.to_dict())
            _dict['time_slots'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ScheduleConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "time_slots": [ScheduleConfigTimeSlotsInner.from_dict(_item) for _item in obj.get("time_slots")] if obj.get("time_slots") is not None else None,
            "frequency": obj.get("frequency") if obj.get("frequency") is not None else 'daily',
            "notification_type": obj.get("notification_type") if obj.get("notification_type") is not None else 'push_notification'
        })
        return _obj


