# coding: utf-8

"""
    PowerManifest Journal API

    API for managing personal journal entries in the PowerManifest life coaching app

    The version of the OpenAPI document: 1.0.0
    Contact: api@powermanifest.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from models.journal.get_journal_analytics200_response_themes_analysis_top_themes_inner import GetJournalAnalytics200ResponseThemesAnalysisTopThemesInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetJournalAnalytics200ResponseThemesAnalysis(BaseModel):
    """
    GetJournalAnalytics200ResponseThemesAnalysis
    """ # noqa: E501
    top_themes: Optional[List[GetJournalAnalytics200ResponseThemesAnalysisTopThemesInner]] = Field(default=None, description="Most frequent themes in entries")
    emerging_patterns: Optional[List[StrictStr]] = Field(default=None, description="New patterns AI has identified")
    __properties: ClassVar[List[str]] = ["top_themes", "emerging_patterns"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetJournalAnalytics200ResponseThemesAnalysis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in top_themes (list)
        _items = []
        if self.top_themes:
            for _item in self.top_themes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['top_themes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetJournalAnalytics200ResponseThemesAnalysis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "top_themes": [GetJournalAnalytics200ResponseThemesAnalysisTopThemesInner.from_dict(_item) for _item in obj.get("top_themes")] if obj.get("top_themes") is not None else None,
            "emerging_patterns": obj.get("emerging_patterns")
        })
        return _obj


