# coding: utf-8

"""
    AI Life Coach API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictBytes, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CoachMessageResponse(BaseModel):
    """
    CoachMessageResponse
    """ # noqa: E501
    response_text: Optional[StrictStr] = None
    response_sound: Optional[Union[StrictBytes, StrictStr]] = None
    voice_usage_cost: Optional[Union[StrictFloat, StrictInt]] = None
    voice_usage_duration: Optional[Union[StrictFloat, StrictInt]] = None
    context_calculation_usage: Optional[Union[StrictFloat, StrictInt]] = None
    tts_usage: Optional[Union[StrictFloat, StrictInt]] = None
    stt_usage: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["response_text", "response_sound", "voice_usage_cost", "voice_usage_duration", "context_calculation_usage", "tts_usage", "stt_usage"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CoachMessageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CoachMessageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "response_text": obj.get("response_text"),
            "response_sound": obj.get("response_sound"),
            "voice_usage_cost": obj.get("voice_usage_cost"),
            "voice_usage_duration": obj.get("voice_usage_duration"),
            "context_calculation_usage": obj.get("context_calculation_usage"),
            "tts_usage": obj.get("tts_usage"),
            "stt_usage": obj.get("stt_usage")
        })
        return _obj


